appname:            'StorMan'
layout:             'main'
server:             '0.0.0.0'
template:           'template_toolkit'
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '<%'
    end_tag:   '%>'
show_errors:        1
error_template:     'error'
default_mime_type:  'text/plain'
logger:             'file'
logger_format:      '%t [%L] %m'
session:            'YAML'
session_dir:        '/opt/StorMan/var/sessions'
admin_role:         'isg'

plugins:
  Auth::Extensible:
    no_default_pages: 1
    no_login_handler: 1
    realms:
      ldap:
        provider:     'LDAPphys'
        server:       'ldap.phys.ethz.ch'
        base_dn:      'ou=Physik Departement,o=ethz,c=ch'
        group_filter: '(objectClass=dphysGroup)'
